# -*- coding: utf-8 -*-
# Databron voor de contentpagina's. Elke week groeit deze lijst; generator = pseo.py

# (slug, meervoud, enkelvoud, werkplek, ritme, praktijkdetail)
BEROEPEN = [
("tandarts","tandartsen","tandarts","tandartspraktijk","lange consultdagen en wachtdiensten","een wachtzaal die er elke ochtend fris bij ligt, sanitair dat altijd in orde is en een teamkeuken waar het aangenaam lunchen is"),
("huisarts","huisartsen","huisarts","huisartsenpraktijk","huisbezoeken, consulten en wachtposten","een propere wachtzaal, opgeruimde consultatieruimtes buiten de spreekuren en een onthaal dat er verzorgd uitziet"),
("arts-specialist","artsen-specialisten","arts-specialist","privépraktijk","ziekenhuisdagen en consultaties aan huis","een privépraktijk die tussen twee consultatiedagen netjes wordt bijgehouden"),
("apotheker","apothekers","apotheker","apotheek","openingsuren en wachtdiensten","een back-office, personeelsruimte en sanitair die buiten de openingsuren worden onderhouden"),
("kinesitherapeut","kinesitherapeuten","kinesitherapeut","kinepraktijk","volle agenda's van vroeg tot laat","behandelzalen, kleedruimte en wachtzaal die er na een drukke dag weer klaar voor zijn"),
("osteopaat","osteopaten","osteopaat","osteopathiepraktijk","korte consulten en een volle agenda","een rustige praktijkruimte en wachtzaal die elke week in orde worden gebracht"),
("psycholoog","psychologen","psycholoog","therapiepraktijk","gesprekken die energie vragen","een warme, opgeruimde praktijkruimte waar cliënten zich meteen welkom voelen"),
("logopedist","logopedisten","logopedist","logopediepraktijk","sessies na schooltijd en tot in de avond","een praktijk met speelhoek en materiaal dat netjes en hygiënisch blijft"),
("dierenarts","dierenartsen","dierenarts","dierenartspraktijk","spoedgevallen en onregelmatige uren","een wachtzaal en balie die er ondanks de drukte verzorgd bij liggen"),
("vroedvrouw","vroedvrouwen","vroedvrouw","praktijk","bevallingen en huisbezoeken op elk uur","een praktijkruimte die klaar is, ook na een nacht van wacht"),
("orthodontist","orthodontisten","orthodontist","orthodontiepraktijk","volle woensdagnamiddagen en schoolvakanties","een wachtzaal vol gezinnen die toch elke dag fris oogt"),
("oogarts","oogartsen","oogarts","oogartsenpraktijk","volle consultatiedagen","onderzoeksruimtes en wachtzaal die buiten de uren worden onderhouden"),
("dermatoloog","dermatologen","dermatoloog","dermatologiepraktijk","een lange wachtlijst en volle dagen","een praktijk die er even verzorgd uitziet als de zorg die u biedt"),
("thuisverpleegkundige","thuisverpleegkundigen","thuisverpleegkundige","kantoor aan huis","vroege rondes en late rondes","een kantoor aan huis dat op orde blijft terwijl u op ronde bent"),
("advocaat","advocaten","advocaat","advocatenkantoor","zittingen, deadlines en dossiers tot 's avonds","een onthaal en vergaderruimte die klanten een verzorgde eerste indruk geven"),
("notaris","notarissen","notaris","notariskantoor","aktes, afspraken en ondertekeningen","vergaderzalen die tussen twee ondertekeningen netjes klaarstaan"),
("gerechtsdeurwaarder","gerechtsdeurwaarders","gerechtsdeurwaarder","kantoor","dagen op de baan en dossierwerk","een kantoor dat bijgehouden wordt terwijl u op verplaatsing bent"),
("bedrijfsrevisor","bedrijfsrevisoren","bedrijfsrevisor","revisorenkantoor","drukke afsluitperiodes","kantoorruimtes die ook in de piekperiode opgeruimd blijven"),
("accountant","accountants","accountant","accountantskantoor","aangifteperiodes en jaarafsluitingen","een kantoor en keuken die netjes blijven, ook als de deadlines zich opstapelen"),
("boekhouder","boekhouders","boekhouder","boekhoudkantoor","btw-aangiftes en afsluitingen","een rustige werkplek, ook in de drukste maanden"),
("architect","architecten","architect","architectenbureau","werfbezoeken en ontwerpdagen","een studio die klanten graag binnenstappen, met een vergadertafel die altijd vrij is"),
("ingenieur","ingenieurs","ingenieur","studiebureau","projecten en werfopvolging","een kantoor dat wordt bijgehouden terwijl u op de werf staat"),
("landmeter","landmeters","landmeter","landmeterskantoor","dagen buiten op het terrein","een kantoor aan huis dat op orde is wanneer u terugkomt van het terrein"),
("interieurarchitect","interieurarchitecten","interieurarchitect","studio","klantbezoeken en ontwerpwerk","een studio en toonruimte die er altijd verzorgd bijliggen"),
("consultant","consultants","consultant","kantoor aan huis","klantdagen en reizen","een thuiskantoor en huis die op orde zijn, ook in de weken dat u veel onderweg bent"),
("it-consultant","IT-consultants","IT-consultant","thuiskantoor","projecten, releases en lange schermdagen","een thuiskantoor dat proper blijft en een huishouden dat draait terwijl u werkt"),
("grafisch-ontwerper","grafisch ontwerpers","grafisch ontwerper","studio","deadlines en creatieve pieken","een studio en huis die opgeruimd zijn, zodat er ruimte blijft in uw hoofd"),
("fotograaf","fotografen","fotograaf","studio","shoots in het weekend en editing tot laat","een studio die klaarstaat voor de volgende shoot"),
("marketingbureau","marketingbureaus","zaakvoerder van een marketingbureau","bureau","campagnes en klantdeadlines","een bureau waar het team graag binnenkomt"),
("coach","coaches","coach","praktijkruimte","sessies, trajecten en opleidingen","een praktijkruimte die rust uitstraalt"),
("vastgoedmakelaar","vastgoedmakelaars","vastgoedmakelaar","immokantoor","bezichtigingen tot 's avonds en op zaterdag","een kantoor dat er verzorgd bijligt voor elke klant die binnenstapt"),
("verzekeringsmakelaar","verzekeringsmakelaars","verzekeringsmakelaar","kantoor","klantafspraken en dossiers","een onthaal en kantoor die vertrouwen uitstralen"),
("bankagent","bankagenten","bankagent","agentschap","klantenafspraken en opvolging","een agentschap dat er buiten de openingsuren netjes bij komt te liggen"),
("zaakvoerder","zaakvoerders","zaakvoerder","bedrijf","volle agenda's en beslissingen die niet wachten","een kantoor dat op orde blijft en een huishouden dat niet op u wacht"),
("kantoor-aan-huis","ondernemers met kantoor aan huis","ondernemer met kantoor aan huis","kantoor aan huis","werk en privé onder één dak","een kantoor aan huis en een woning die allebei op orde zijn"),
("bakker","bakkers","bakker","bakkerij","nachtwerk en vroege ochtenden","een privéhuishouden dat draait, terwijl u slaapt of in de bakkerij staat"),
("slager","slagers","slager","slagerij","lange winkeldagen en feestperiodes","een huishouden dat op orde is, ook in de drukke eindejaarsweken"),
("kapper","kappers","kapper","kapsalon","lange salondagen en zaterdagen","een salon en huis die er verzorgd bij blijven liggen"),
("schoonheidsspecialist","schoonheidsspecialisten","schoonheidsspecialist","instituut","behandelingen tot 's avonds","een instituut dat rust en hygiëne uitstraalt"),
("horeca-uitbater","horeca-uitbaters","horeca-uitbater","zaak","avonden en weekends in de zaak","een privéhuishouden dat draait, zodat uw vrije dag ook echt vrij is"),
]

# (slug, titel, h1-zin, korte omschrijving, taken, beeld)
DIENSTEN = [
("poetshulp-aan-huis","Poetshulp aan huis voor ondernemers","Meer dan poetshulp aan huis","Een vaste Zondag die uw huis bijhoudt, geboekt op uw vennootschap.",["Alle ruimtes poetsen","Stofzuigen en dweilen","Keuken en badkamers","Ramen langs binnen","Kasten opruimen"],"01-poetsen"),
("strijkhulp","Strijkhulp aan huis","Strijkhulp aan huis, elke week","Uw strijk gebeurt thuis, elke week, door dezelfde persoon.",["Hemden en blouses strijken","Bedlinnen en handdoeken","Vouwen en opbergen","Kleding klaarhangen voor de week"],"06-strijken"),
("wasservice-aan-huis","Wasservice aan huis","De was, zonder dat u eraan denkt","Wassen, drogen, vouwen en opbergen, gewoon bij u thuis.",["Wassen en drogen","Vouwen en opbergen","Bedden verschonen","Handdoeken en linnen op peil"],"05-wassen"),
("kookhulp-aan-huis","Kookhulp aan huis","Thuiskomen en het eten staat klaar","Uw Zondag kookt bij u thuis met verse boodschappen.",["Koken voor het gezin","Weekmenu opstellen","Maaltijden voorbereiden","Keuken opruimen na het koken"],"04-koken"),
("maaltijden-voor-de-week","Maaltijden voor de week","Een volle koelkast voor de hele week","Gezonde maaltijden, vooraf bereid en klaar om op te warmen.",["Weekmenu klaarzetten","Gezonde schotels uit ons menu","Porties voor de werkweek","Boodschappen inbegrepen"],"eten-3-bakjes"),
("boodschappenhulp","Boodschappenhulp","De boodschappen, ook de vergeten dingen","Uw Zondag doet de boodschappen en vult de voorraad aan.",["Wekelijkse boodschappen","Voorraad bijhouden","Markt en bakker","Pakjes ophalen"],"04-koken"),
("kinderen-ophalen-van-school","Kinderen ophalen van school","De kinderen opgehaald, elke dag","Een vaste, vertrouwde persoon die uw kinderen ophaalt en opvangt.",["Ophalen aan de schoolpoort","Naar training of muziekschool brengen","Vieruurtje klaarzetten","Opvang tot u thuis bent"],"03-au-pair"),
("naschoolse-opvang-aan-huis","Naschoolse opvang aan huis","Opvang na school, gewoon thuis","Uw kinderen blijven na school in hun eigen omgeving.",["Opvang na school","Samen eten","Badje en pyjama","Naar bed brengen"],"02-kinderopvang"),
("huiswerkbegeleiding-aan-huis","Huiswerkbegeleiding aan huis","Rust aan de keukentafel","Hulp bij huiswerk en planning, door dezelfde vertrouwde persoon.",["Huiswerk opvolgen","Lessen helpen leren","Boekentas klaarzetten","Agenda en planning nakijken"],"03-au-pair"),
("kinderoppas-overdag","Kinderoppas overdag","Een vaste oppas voor de kleinsten","Overdag een vaste oppas bij u thuis, in het ritme van uw gezin.",["Op de kinderen passen","Spelen en buiten gaan","Eten en dutjes","Huishouden tussendoor"],"02-kinderopvang"),
("tuinonderhoud","Tuinonderhoud","Een tuin om van te genieten","Licht tuinonderhoud, elke week of elke maand.",["Gras afrijden","Onkruid wieden","Planten water geven","Hagen bijknippen"],"07-tuin"),
("gras-maaien","Gras maaien","Het gras gemaaid, zonder dat u het vraagt","Een vaste afspraak voor het gras, het hele seizoen.",["Gras afrijden","Kanten afwerken","Gras opruimen","Terras vegen"],"07-tuin"),
("terras-reinigen","Terras reinigen","Een terras dat klaarligt voor de zomer","Terras en buitenruimte proper en opgeruimd.",["Terras kuisen","Tuinmeubels afnemen","Bloempotten verzorgen","Buitenruimte opruimen"],"07-tuin"),
("hond-uitlaten","Hond uitlaten","Uw hond, verzorgd en uitgelaten","Uw hond gaat elke dag op tijd naar buiten.",["Hond uitlaten","Eten en water","Kat verzorgen","Mand en speelgoed proper"],"07-tuin"),
("huisoppas-tijdens-vakantie","Huisoppas tijdens uw vakantie","Een huis dat klaarstaat bij uw terugkeer","Uw huis wordt bijgehouden terwijl u weg bent.",["Post en pakjes sorteren","Planten water geven","Het huis luchten en nakijken","Koelkast vullen voor uw terugkeer"],"01-poetsen"),
("kantoorschoonmaak","Kantoorschoonmaak","Een kantoor dat elke ochtend klaarstaat","Uw kantoor wordt buiten de werkuren onderhouden door een vaste persoon.",["Bureaus en vergaderruimte","Sanitair en keuken","Vloeren","Afval en recyclage"],"01-poetsen"),
("praktijkschoonmaak","Praktijkschoonmaak","Een praktijk die vertrouwen uitstraalt","Uw praktijk en wachtzaal, verzorgd door dezelfde persoon.",["Wachtzaal en onthaal","Consultatieruimtes","Sanitair","Personeelsruimte"],"01-poetsen"),
("ramen-binnen-wassen","Ramen langs binnen wassen","Helder zicht, elke week","Ramen langs binnen, spiegels en glazen deuren.",["Ramen langs binnen","Spiegels","Glazen deuren","Vensterbanken"],"01-poetsen"),
("droogkuis-en-regelwerk","Droogkuis en regelwerk","Het regelwerk, geregeld","De kleine ritjes en taken die anders blijven liggen.",["Droogkuis wegbrengen en ophalen","Pakjes terugsturen","Apotheek en bakker","Wagen naar de carwash"],"06-strijken"),
("huishoudelijke-hulp-voor-ondernemers","Huishoudelijke hulp voor ondernemers","Huishoudelijke hulp, geboekt op uw zaak","Eén vaste Zondag voor alles in en rond uw huis en uw zaak.",["Poetsen en huishouden","Was en strijk","Koken en boodschappen","De kinderen","Tuin en kantoor"],"01-poetsen"),
]

# (slug, vraag/titel, lead, secties[(h2, tekst)], faq[(v,a)])
GIDSEN = [
("dienstencheques-vennootschap","Kan een vennootschap dienstencheques kopen?","Nee. Dienstencheques zijn voorbehouden aan natuurlijke personen. Voor huishoudelijke hulp via uw vennootschap is er een ander, volledig wettelijk alternatief.",[
 ("Waarom een vennootschap geen dienstencheques kan gebruiken","Dienstencheques zijn ontworpen voor particulieren. De gebruiker moet een natuurlijke persoon zijn die de cheques op eigen naam koopt. Een vennootschap valt daar niet onder, ook niet wanneer de zaakvoerder thuis werkt of het huis deels als kantoor gebruikt."),
 ("Het alternatief: een gewone dienstenfactuur","Zondags werkt met een gewone dienstenfactuur op naam van uw vennootschap. Die factuur kan zowel uw kantoor of praktijk als uw privéruimtes omvatten. Voor het privégedeelte wordt een forfaitair voordeel van alle aard aangerekend."),
 ("Wat dat in de praktijk betekent","U krijgt één vaste Zondag, op een vaste dag, met één factuur per maand. Uw accountant verwerkt het kantoorgedeelte als beroepskost en het privégedeelte als voordeel van alle aard.")],
 [("Kan ik als zaakvoerder zelf dienstencheques kopen?","Ja, als natuurlijke persoon kan dat. Maar dan betaalt u privé en kan de vennootschap de kosten niet dragen."),("Moet ik mijn accountant betrekken?","Ja. Laat uw accountant de verwerking steeds bevestigen voor uw eigen situatie.")]),
("huishoudhulp-via-vennootschap","Huishoudhulp via uw vennootschap: hoe werkt dat?","Een vennootschap mag huishoudelijke diensten inkopen voor kantoor en woning. Met de juiste structuur is dat volledig correct en transparant.",[
 ("Kantoor en woning op één factuur","Zondags factureert aan uw vennootschap. Op de factuur staat duidelijk welk deel beroepsmatig is en welk deel privé. Zo heeft uw accountant alles wat nodig is."),
 ("Het privégedeelte als voordeel van alle aard","Voor de privéruimtes wordt een forfaitair voordeel van alle aard aangerekend aan de bedrijfsleider. Dat forfait is wettelijk vastgelegd en geldt voor huispersoneel dat via een onderneming met mensen in dienst werkt."),
 ("Twee voorwaarden","De prestaties moeten regelmatig zijn en gebeuren via een onderneming met mensen in dienst. Een abonnement bij Zondags voldoet aan beide.")],
 [("Is dit fiscaal advies?","Nee. Zondags levert de dienst en een duidelijke factuur. Uw accountant bevestigt de verwerking voor uw situatie."),("Werkt dit ook voor een eenmanszaak?","De structuur is bedoeld voor vennootschappen. Bespreek uw situatie met uw accountant.")]),
("voordeel-alle-aard-huispersoneel","Voordeel van alle aard voor huispersoneel uitgelegd","Wanneer uw vennootschap huishoudelijke hulp in uw woning betaalt, wordt dat privévoordeel forfaitair gewaardeerd. Zo werkt het.",[
 ("Wat is een voordeel van alle aard?","Een voordeel van alle aard is een voordeel dat u als bedrijfsleider van uw vennootschap krijgt, niet in geld maar in natura. Denk aan een bedrijfswagen of, hier, huishoudelijke hulp in uw woning."),
 ("Forfaitair gewaardeerd","Voor huispersoneel bestaat een wettelijk forfait per jaar voor voltijdse prestaties. Bij deeltijdse prestaties wordt dat forfait in verhouding toegepast. Het voordeel komt op uw fiche 281.20."),
 ("Wanneer het forfait geldt","Het forfait geldt wanneer de prestaties regelmatig zijn en gebeuren via een onderneming met mensen in dienst, of via eigen personeel. Bij een zelfstandige poetshulp wordt het voordeel anders gewaardeerd.")],
 [("Hoe hoog is het forfait?","Het bedrag wordt wettelijk vastgelegd en kan wijzigen. Uw accountant kent het actuele bedrag."),("Komt dit op mijn fiche?","Ja, het voordeel wordt opgenomen op uw fiche 281.20.")]),
("fiche-28120-huispersoneel","Huishoudelijke hulp en uw fiche 281.20","Wie als bedrijfsleider huishoudelijke hulp via de vennootschap krijgt, ziet dat terug op de fiche 281.20. Dit is wat u moet weten.",[
 ("Waarom het op uw fiche komt","Het privégedeelte van de huishoudelijke hulp is een voordeel van alle aard. Dat wordt, zoals elk voordeel voor een bedrijfsleider, op de fiche 281.20 vermeld."),
 ("Wat Zondags aanlevert","U krijgt maandelijks een duidelijke factuur met de splitsing tussen kantoor en privé. Daarmee kan uw accountant het voordeel correct berekenen."),
 ("Samen met uw accountant","Bespreek bij de start even met uw accountant hoe hij het voordeel wil verwerken. Dan loopt het daarna vanzelf.")],
 [("Moet ik zelf iets berekenen?","Nee, uw accountant verwerkt het voordeel op basis van de facturen."),("Wat als ik enkel mijn kantoor laat onderhouden?","Dan is er geen privégedeelte en dus geen voordeel van alle aard voor de woning.")]),
("kantoor-aan-huis-schoonmaak","Schoonmaak van een kantoor aan huis: kantoor en privé correct gesplitst","Werkt u vanuit huis? Dan wordt een deel van de huishoudelijke hulp beroepsmatig. Zo houdt u het overzichtelijk.",[
 ("Twee soorten ruimtes","Uw kantoor, wachtruimte of praktijk zijn beroepsmatig. Keuken, slaapkamers en badkamer zijn privé. Op de factuur van Zondags staat die splitsing duidelijk."),
 ("Waarom een vaste persoon het eenvoudig maakt","Omdat steeds dezelfde Zondag komt, op een vast moment, is het ook eenvoudig om bij te houden welke tijd naar welke ruimte gaat."),
 ("Wat u met uw accountant bespreekt","De verhouding tussen kantoor en privé, en hoe het privégedeelte als voordeel van alle aard wordt verwerkt.")],
 [("Is btw recupereerbaar?","Op het beroepsmatige deel in principe wel, op het privégedeelte in principe niet. Laat uw accountant dit bevestigen."),("Kan ik later uitbreiden?","Ja, extra uren bijboeken kan altijd.")]),
("zelfstandige-poetshulp-of-firma","Zelfstandige poetshulp of een firma met personeel: wat is het verschil?","Het verschil lijkt klein, maar fiscaal en praktisch maakt het veel uit. Een overzicht.",[
 ("Fiscaal","Voor een bedrijfsleider die huishoudelijke hulp via de vennootschap laat betalen, geldt het forfaitaire voordeel enkel wanneer de hulp via een onderneming met mensen in dienst of via eigen personeel komt. Bij een zelfstandige poetshulp wordt het voordeel anders gewaardeerd."),
 ("Zekerheid","Een Zondag is in dienst van Zondags, gescreend en verzekerd. Bij ziekte of verlof zoeken wij een oplossing, u hoeft niets te regelen."),
 ("Continuïteit","U krijgt een vaste persoon en een vast plan, met een onderneming die achter die afspraak staat.")],
 [("Is mijn Zondag verzekerd?","Uw Zondag is in dienst van Zondags."),("Komt er een vervanger bij verlof?","Wij bekijken samen met u de beste oplossing bij verlof of ziekte.")]),
("regelmatige-prestaties","Waarom regelmatige prestaties belangrijk zijn","Regelmaat is niet alleen prettig, het is ook een voorwaarde voor de fiscale behandeling van huishoudelijke hulp via uw vennootschap.",[
 ("Regelmaat als voorwaarde","Het forfaitaire voordeel van alle aard voor huispersoneel veronderstelt prestaties die regelmatig zijn, niet occasioneel."),
 ("Een abonnement is precies dat","Bij Zondags boekt u een vast aantal uren per maand. Dezelfde persoon, op dezelfde dag, op hetzelfde uur."),
 ("En praktisch","Regelmaat zorgt ook voor kwaliteit: uw Zondag kent uw huis, uw gewoontes en uw voorkeuren.")],
 [("Kan ik eens een week overslaan?","Bespreek het met ons. De uren vervallen niet."),("Is een maandelijks abonnement opzegbaar?","Ja, maandelijks opzegbaar.")]),
("dienstenfactuur-woning-en-kantoor","Eén dienstenfactuur voor woning en kantoor","Hoe ziet een factuur van Zondags eruit, en waarom is dat handig voor uw boekhouding?",[
 ("Duidelijke splitsing","Elke factuur toont de prestaties en de splitsing tussen beroepsmatige en privéruimtes."),
 ("Maandelijks","U krijgt één factuur per maand, op naam van uw vennootschap."),
 ("Klaar voor uw accountant","Met de factuur kan uw accountant zowel de kosten als het voordeel van alle aard correct verwerken.")],
 [("Kan de factuur naar mijn accountant?","Ja, dat regelen we graag zo."),("Staan extra uren apart vermeld?","Ja, extra uren staan duidelijk op de factuur.")]),
("btw-huishoudelijke-diensten","Btw op huishoudelijke diensten via uw vennootschap","Kan uw vennootschap de btw recupereren op huishoudelijke hulp? Het hangt af van de ruimtes.",[
 ("Beroepsmatige ruimtes","Voor uw kantoor, praktijk of wachtzaal is de btw in principe recupereerbaar, zoals bij andere beroepskosten."),
 ("Privéruimtes","Voor de privéruimtes is de btw in principe niet aftrekbaar."),
 ("Laat het bevestigen","Uw accountant beoordeelt de btw-behandeling voor uw situatie. Zondags levert een factuur die dat eenvoudig maakt.")],
 [("Staat de btw apart op de factuur?","Ja, zoals op elke dienstenfactuur."),("Wie beslist over de aftrek?","Uw accountant, op basis van uw situatie.")]),
("hoeveel-uur-huishoudhulp","Hoeveel uur huishoudhulp hebt u nodig?","Een eerlijke inschatting per situatie, zodat u niet te veel en niet te weinig boekt.",[
 ("Een appartement of kleine woning","Voor het basisonderhoud van een kleinere woning volstaat vaak een halve dag per week. Komt er strijk of koken bij, dan reken je beter ruimer."),
 ("Een gezinswoning","Een gezin met kinderen heeft meestal baat bij een of twee vaste dagen per week, zeker wanneer ook de was, het koken of het ophalen van de kinderen erbij hoort."),
 ("Woning en kantoor","Komt uw kantoor of praktijk erbij, dan stemmen we de uren af op de grootte en het gebruik. Tijdens de gratis kennismaking maken we samen een realistische inschatting.")],
 [("Kan ik later bijsturen?","Ja, extra uren bijboeken kan altijd en ze vervallen niet."),("Is de kennismaking echt gratis?","De eerste 2 uur zijn gratis.")]),
("huishoudhulp-zonder-dienstencheques","Huishoudhulp zonder dienstencheques","Er bestaat huishoudelijke hulp buiten het dienstenchequesysteem. Voor ondernemers is dat vaak de logische keuze.",[
 ("Waarom buiten het systeem","Dienstencheques zijn voor particulieren. Wie zijn huishoudelijke hulp via de vennootschap wil laten lopen, of meer wil dan schoonmaak, kiest voor een gewone dienstverlener."),
 ("Meer dan schoonmaak","Een Zondag doet ook de was, kookt, haalt de kinderen op, doet boodschappen en houdt de tuin bij."),
 ("Eén vaste persoon","Steeds dezelfde persoon, die uw huis en uw gewoontes kent.")],
 [("Is dit duurder?","De prijs hangt af van uw situatie. U krijgt een voorstel op maat na de kennismaking."),("Werkt dit ook voor mijn kantoor?","Ja, kantoor of praktijk kan erbij.")]),
("dienstencheques-geen-aftrek-meer","Dienstencheques en de afgeschafte fiscale aftrek","In Vlaanderen is de fiscale aftrek voor dienstencheques afgeschaft. Wat betekent dat voor ondernemers?",[
 ("Wat veranderde","Sinds 2025 levert het gebruik van dienstencheques in Vlaanderen geen fiscale aftrek meer op."),
 ("Wat dat voor ondernemers betekent","Wie als bedrijfsleider huishoudelijke hulp zoekt, bekijkt beter het alternatief via de vennootschap, met een gewone dienstenfactuur."),
 ("Laat het doorrekenen","Uw accountant kan voor uw situatie vergelijken wat de beste keuze is.")],
 [("Kan ik beide combineren?","Bespreek dat met uw accountant."),("Wat doet Zondags anders?","Wij werken met eigen mensen in dienst en een gewone factuur aan uw vennootschap.")]),
("vaste-huishoudhulp-voordelen","Waarom een vaste huishoudhulp zoveel verschil maakt","Dezelfde persoon, op dezelfde dag, op hetzelfde uur. Vier redenen waarom dat telt.",[
 ("Vertrouwen","U geeft uw sleutel aan iemand die u kent. Dat maakt het verschil, zeker met kinderen in huis."),
 ("Kwaliteit","Uw Zondag kent uw huis en weet hoe u het graag heeft. U hoeft niets telkens opnieuw uit te leggen."),
 ("Rust","Het huishouden wordt een vast ritme in plaats van iets dat u telkens moet organiseren.")],
 [("Wat als mijn Zondag ziek is?","Dan bekijken wij met u een oplossing."),("Kan ik van Zondag wisselen?","Ja, als het niet klikt, zoeken we samen een andere match.")]),
("intakegesprek","Het intakegesprek: wat mag u verwachten?","Voor uw Zondag begint, komen we langs. Dit gebeurt er tijdens de intake.",[
 ("Kennismaken","We bekijken uw woning of kantoor en luisteren naar wat u nodig hebt."),
 ("Uw zondagsplan","Samen leggen we vast wat er gebeurt, wanneer, en hoe u het graag heeft. Dat noemen we uw zondagsplan."),
 ("De start","Vanaf de eerste week komt dezelfde persoon op hetzelfde moment.")],
 [("Hoe lang duurt de intake?","Reken op een goed uur."),("Is de kennismaking gratis?","De eerste 2 uur zijn gratis.")]),
("zondagsplan","Wat is een zondagsplan?","Het zondagsplan is de afspraak tussen u en uw Zondag: wat, wanneer en hoe.",[
 ("Wat erin staat","De taken per bezoek, de vaste dag en het uur, en uw voorkeuren. Van welke producten tot waar de sleutel ligt."),
 ("Waarom het werkt","Omdat alles vooraf is afgesproken, hoeft u niets te regelen. Uw Zondag weet wat er moet gebeuren."),
 ("Bijsturen","Het plan is niet in steen gebeiteld. We passen het aan wanneer uw situatie verandert.")],
 [("Kan ik taken toevoegen?","Ja, het plan groeit mee."),("Wie maakt het plan?","We maken het samen tijdens de intake.")]),
("huishouden-en-zaak-combineren","Een zaak runnen en een huishouden: zo houdt u het vol","Ondernemers combineren vaak twee voltijdse jobs: hun zaak en hun huishouden. Een paar inzichten.",[
 ("Waar uw tijd naartoe gaat","Was, koken, boodschappen, ophalen, opruimen: het zijn kleine taken die samen al snel een volle dag per week vragen."),
 ("Uitbesteden wat geen waarde toevoegt","Uw tijd is het meest waard in uw zaak en bij uw gezin. Taken die iemand anders even goed kan doen, besteedt u beter uit."),
 ("Een vast ritme","Met een vaste Zondag op een vaste dag verdwijnt het regelwerk uit uw hoofd.")],
 [("Waar begin ik best mee?","Met de taken die u het meest tijd of energie kosten."),("Kan ik klein beginnen?","Ja, en later uitbreiden.")]),
("kinderen-ophalen-als-ondernemer","Kinderen ophalen als ondernemer: vaste hulp na school","Om 15u30 aan de schoolpoort staan is voor veel ondernemers onmogelijk. Er is een vaste oplossing.",[
 ("Een vertrouwd gezicht","Uw Zondag haalt de kinderen op, brengt ze naar hun activiteiten en vangt ze thuis op."),
 ("Meer dan opvang","Vieruurtje, huiswerk, samen eten: uw Zondag combineert het met het huishouden."),
 ("Altijd dezelfde persoon","Kinderen hebben nood aan een vast gezicht. Daarom komt steeds dezelfde Zondag.")],
 [("Kan mijn Zondag rijden?","Dat bespreken we tijdens de intake."),("Ook tijdens schoolvakanties?","Dat stemmen we af in uw zondagsplan.")]),
("gezond-eten-drukke-week","Gezond eten in een drukke werkweek","Geen tijd om te koken betekent niet dat u ongezond moet eten. Zo pakt u het aan.",[
 ("Vooraf plannen","Een weekmenu voorkomt dat u 's avonds moet improviseren."),
 ("Laten koken of laten meebrengen","Uw Zondag kookt bij u thuis met verse boodschappen, of brengt gezonde schotels uit ons menu mee."),
 ("Een volle koelkast","Wanneer u thuiskomt, staat het eten klaar.")],
 [("Zijn er vegetarische opties?","Ja, en we passen aan bij allergieën."),("Wisselt het menu?","Het menu wisselt met de seizoenen.")]),
("checklist-praktijkschoonmaak","Checklist: schoonmaak van een praktijk","Wat moet er dagelijks, wekelijks en maandelijks gebeuren in een praktijk? Een praktische checklist.",[
 ("Dagelijks of per bezoek","Wachtzaal opruimen, sanitair, deurklinken en balie, afval."),
 ("Wekelijks","Vloeren grondig, consultatieruimtes, keuken van het team, ramen langs binnen."),
 ("Maandelijks","Kasten, plinten en moeilijk bereikbare plaatsen.")],
 [("Gebeurt het buiten de uren?","Ja, we stemmen het af op uw spreekuren."),("Kan mijn woning erbij?","Ja, woning en praktijk kunnen samen.")]),
("checklist-kantoorschoonmaak","Checklist: schoonmaak van een klein kantoor","Een klein kantoor proper houden zonder het zelf te moeten doen. Deze checklist helpt.",[
 ("Wekelijks","Bureaus, vergadertafel, keuken en sanitair, vloeren, afval en recyclage."),
 ("Maandelijks","Ramen langs binnen, kasten, plinten en stoelen."),
 ("Extra","Leveringen aannemen en de koffiehoek aanvullen.")],
 [("Buiten de werkuren?","Ja, dat kan."),("Ook voor een kantoor aan huis?","Ja, met een duidelijke splitsing op de factuur.")]),
("checklist-huis-tijdens-vakantie","Checklist: uw huis tijdens de vakantie","Met een gerust hart op reis. Dit regelt u best voor uw vertrek.",[
 ("Tijdens uw afwezigheid","Post en pakjes ophalen, planten water geven, het huis luchten en nakijken."),
 ("Dieren","Hond of kat verzorgen, eten en water, uitlaten."),
 ("Bij uw terugkeer","Bedden opgemaakt, koelkast gevuld en een huis dat klaarstaat.")],
 [("Komt dezelfde persoon?","Ja, uw vaste Zondag."),("Kan dit los geboekt worden?","Dit hoort bij uw zondagsplan.")]),
("huishoudhulp-directie-en-talent","Huishoudelijke hulp voor directie en sleutelfiguren","Voor bedrijfsleiders en directie is tijd het schaarste goed. Een vaste Zondag geeft het terug.",[
 ("Volledig huishouden","Poetsen, was, koken, de kinderen en de tuin: alles in één vast plan."),
 ("Via de vennootschap","Op één factuur aan de vennootschap, met een duidelijke splitsing."),
 ("Discreet en vast","Steeds dezelfde, gescreende persoon.")],
 [("Kan dit voor meerdere bestuurders?","Bespreek het met ons en uw accountant."),("Hoe start ik?","Met een vrijblijvende aanvraag.")]),
("huishoudhulp-of-schoonmaakbedrijf","Huishoudhulp of schoonmaakbedrijf: wat past bij u?","Een schoonmaakbedrijf maakt schoon. Een Zondag doet meer. Een vergelijking.",[
 ("Een schoonmaakbedrijf","Vaak wisselende ploegen, gericht op schoonmaak alleen."),
 ("Een Zondag","Eén vaste persoon voor het huishouden, de was, het koken, de kinderen en de tuin, en voor uw kantoor."),
 ("Wanneer wat","Voor grote kantoorgebouwen is een schoonmaakbedrijf logisch. Voor ondernemers met een woning en een kleiner kantoor of praktijk is een Zondag de eenvoudigste keuze.")],
 [("Doet Zondags grote kantoren?","Wij richten ons op ondernemers, praktijken en kleinere kantoren."),("Kan ik combineren?","Ja, woning en kantoor in één plan.")]),
("vragen-voor-uw-accountant","Vijf vragen om aan uw accountant te stellen","Voor u huishoudelijke hulp via uw vennootschap laat lopen, stelt u best deze vragen.",[
 ("Over het voordeel van alle aard","Hoe wordt het privégedeelte verwerkt en op welke fiche komt het?"),
 ("Over de btw","Welk deel van de btw is recupereerbaar in mijn situatie?"),
 ("Over de verhouding","Welke verhouding tussen kantoor en privé is redelijk voor mijn woning?")],
 [("Kan Zondags met mijn accountant praten?","Ja, wij bezorgen graag de facturen rechtstreeks."),("Wat als mijn accountant twijfelt?","Dan bekijken we samen de documenten.")]),
]

# (slug, titel, doelgroep-zin, lead, voordelen)
JOBS = [
("studentenjob-huishouden","Studentenjob in het huishouden","studenten vanaf 18 jaar","Een studentenjob met vaste uren, bij vaste klanten, in de buurt van uw kot of thuis.",["Vaste dagen naast je lessen","Werk in de buurt","Afwisselend: huishouden, koken, kinderen","Verloning boven het barema"]),
("bijverdienen-als-student","Bijverdienen als student","studenten die een vaste bijverdienste zoeken","Bijverdienen met vaste uren, zonder avonden en zonder weekends.",["Je kiest zelf hoeveel dagen","Geen avond- of weekendwerk","Vaste klanten","Verplaatsingen vergoed"]),
("flexi-job-huishouden","Flexi-job of bijverdienste in het huishouden","wie naast een hoofdjob wil bijverdienen","Bijverdienen naast uw hoofdjob, met vaste uren bij vaste klanten. Uw statuut bekijken we samen.",["Vaste uren die passen naast uw job","Werk in de buurt","Afwisselend werk","Alles in orde op papier"]),
("flexi-job-na-je-werk","Bijverdienen naast je vaste job","werknemers die extra willen verdienen","Een paar uur per week extra, op vaste momenten, bij mensen die weten wat u komt doen.",["Vaste momenten","Geen wisselende adressen","Vaste klanten","Verloning boven het barema"]),
("deeltijds-werk-overdag","Deeltijds werk overdag","wie deeltijds en overdag wil werken","Deeltijds werk met vaste uren overdag. Geen avonden, geen weekends.",["Vaste dagen","Uren overdag","Vaste klanten","Vast contract"]),
("job-zonder-weekendwerk","Een job zonder weekendwerk","wie de weekends vrij wil houden","Uw weekends blijven vrij. U werkt op vaste weekdagen.",["Geen weekends","Geen avonden","Vaste adressen","Verloning boven het barema"]),
("job-binnen-de-schooluren","Een job binnen de schooluren","ouders die werken tijdens de schooluren","Werken terwijl de kinderen op school zitten.",["Uren die passen bij de school","Vaste dagen","Werk in de buurt","Vast contract"]),
("vacature-huishoudhulp-vast-contract","Vacature huishoudhulp met vast contract","wie zekerheid zoekt","Een vast contract, vaste uren en vaste klanten.",["Vast contract","Vaste uren","Vaste klanten","Verplaatsingen vergoed"]),
("huishoudhulp-zonder-diploma","Huishoudhulp worden zonder diploma","wie zonder specifiek diploma aan de slag wil","Wat telt, is dat u graag voor anderen zorgt en betrouwbaar bent.",["Geen diploma nodig","Wij leren u de werking","Vaste klanten","Verloning boven het barema"]),
("herintreden-na-een-pauze","Herintreden na een pauze","wie na een tijd thuis opnieuw wil werken","Opnieuw beginnen met vaste uren en een duidelijk plan.",["Rustige start","Vaste uren","Vast plan per klant","Verloning boven het barema"]),
("job-voor-werkzoekenden","Een job voor werkzoekenden","werkzoekenden","Snel aan de slag met vaste uren bij vaste klanten.",["Snel starten","Vast contract mogelijk","Vaste klanten","Verplaatsingen vergoed"]),
("job-met-eigen-wagen","Een job met je eigen wagen","wie een rijbewijs en eigen wagen heeft","Met uw wagen kunt u ook boodschappen doen en kinderen ophalen.",["Verplaatsingen vergoed","Afwisselende taken","Vaste klanten","Vaste uren"]),
("kinderoppas-job","Kinderoppas als job","wie graag met kinderen werkt","Kinderen ophalen, opvangen en begeleiden bij een vast gezin.",["Vast gezin","Vaste uren","Ook huishouden mogelijk","Verloning boven het barema"]),
("tuinjob","Een job in de tuin","wie graag buiten werkt","Gras, hagen, onkruid en terras bij vaste klanten.",["Buiten werken","Vaste klanten","Afwisseling met binnenwerk","Verloning boven het barema"]),
("kookjob-aan-huis","Koken bij mensen thuis","wie graag kookt","Koken voor gezinnen, met verse boodschappen, bij u in de buurt.",["Koken voor vaste gezinnen","Boodschappen inbegrepen","Vaste uren","Verloning boven het barema"]),
("strijkjob","Een strijkjob aan huis","wie graag strijkt","Strijken bij vaste klanten thuis, op vaste dagen.",["Vaste dagen","Vaste klanten","Rustig werk","Verloning boven het barema"]),
("job-kantoorschoonmaak","Job in kantoorschoonmaak","wie kantoren en praktijken wil onderhouden","Kantoren en praktijken onderhouden, buiten de werkuren of overdag.",["Vaste adressen","Vaste uren","Zelfstandig werken","Verloning boven het barema"]),
("job-voor-ouders","Een flexibele job voor ouders","ouders die werk en gezin willen combineren","Werk dat rekening houdt met uw gezin.",["Uren die u zelf mee kiest","Geen weekends","Werk in de buurt","Vast contract"]),
("zij-instromer-huishoudhulp","Overstappen naar een job als Zondag","wie van richting wil veranderen","Een nieuwe start in een job waar u echt verschil maakt.",["Rustige opstart","Vaste klanten","Afwisselend werk","Verloning boven het barema"]),
("eerste-job-na-school","Je eerste job na school","schoolverlaters vanaf 18 jaar","Een eerste job met vaste uren en duidelijke afspraken.",["Vaste uren","Duidelijk plan","Vaste klanten","Verloning boven het barema"]),
("job-voor-55-plussers","Een job voor 55-plussers","ervaren werkkrachten","Uw ervaring is welkom. Vaste uren en vaste klanten.",["Vaste uren","Vaste klanten","Geen avonden","Verloning boven het barema"]),
("job-met-vaste-klanten","Een job met vaste klanten","wie liever niet elke dag naar een ander adres gaat","Altijd dezelfde klanten, die u kent en die u kennen.",["Vaste klanten","Vaste dagen","Vertrouwen","Verloning boven het barema"]),
("afwisselende-job","Een afwisselende job","wie niet acht uur hetzelfde wil doen","Huishouden, koken, tuin, boodschappen of de kinderen. Nooit acht uur hetzelfde.",["Afwisselende taken","Vaste klanten","Vaste uren","Verloning boven het barema"]),
("job-zonder-avondwerk","Een job zonder avondwerk","wie 's avonds thuis wil zijn","U werkt overdag en bent 's avonds vrij.",["Geen avonden","Geen weekends","Vaste uren","Verloning boven het barema"]),
("job-als-huishoudhulp-voor-bedrijven","Werken als huishoudhulp voor ondernemers","wie bij ondernemers en praktijken wil werken","U werkt bij ondernemers, artsen en vrije beroepen, thuis en op kantoor.",["Vaste klanten","Woning en kantoor","Afwisselend werk","Verloning boven het barema"]),
]

# (plaats, postcode, zone)
PLAATSEN = [
("Kortrijk","8500","kortrijk"),("Marke","8510","kortrijk"),("Heule","8501","kortrijk"),("Bissegem","8501","kortrijk"),("Aalbeke","8511","kortrijk"),
("Bellegem","8510","kortrijk"),("Rollegem","8510","kortrijk"),("Wevelgem","8560","kortrijk"),("Gullegem","8560","kortrijk"),("Moorsele","8560","kortrijk"),
("Menen","8930","grens"),("Lauwe","8930","grens"),("Rekkem","8930","grens"),("Wervik","8940","grens"),("Geluwe","8940","grens"),
("Harelbeke","8530","leie"),("Kuurne","8520","kortrijk"),("Zwevegem","8550","schelde"),("Deerlijk","8540","leie"),("Waregem","8790","leie"),
("Anzegem","8570","schelde"),("Avelgem","8580","schelde"),("Lendelede","8860","midden"),("Ledegem","8880","midden"),("Moorslede","8890","midden"),
("Izegem","8870","midden"),("Ingelmunster","8770","midden"),("Roeselare","8800","midden"),("Rumbeke","8800","midden"),("Hooglede","8830","midden"),
("Staden","8840","midden"),("Lichtervelde","8810","midden"),("Ardooie","8850","midden"),("Meulebeke","8760","leie"),("Tielt","8700","leie"),
("Oostrozebeke","8780","leie"),("Wielsbeke","8710","leie"),("Dentergem","8720","leie"),("Zulte","9870","leie"),("Pittem","8740","leie"),
("Ieper","8900","westhoek"),("Zonnebeke","8980","westhoek"),("Oudenaarde","9700","ardennen"),("Kruisem","9770","ardennen"),("Kooigem","8510","kortrijk"),
]
